federation_version: '=2.4.7'
subgraphs:
  tracks:
    routing_url: http://subgraph-tracks:4001/graphql
    schema:
      file:
        ../subgraph-tracks/src/schema.graphql
  reviews:
    routing_url: http://subgraph-reviews:4002/graphql
    schema:
      file:
        ../subgraph-reviews/src/schema.graphql